### ISSUE TITLE
ERROR: No matching distribution found for imgstitch

### ISSUE THREAD

**Issue by Durys** [brianpinto91/image-stiching#2]
Hey,

Just to let you know, running the given command gives the error from the title:

$ pip install -i https://test.pypi.org/simple/ imgstitch
Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement imgstitch (from versions: none)
ERROR: No matching distribution found for imgstitch

specs: 
$ pip -V
pip 21.3.1 from c:\users\zofia durys\desktop\kpai\venv\lib\site-packages\pip (python 3.6)
$ python -V
Python 3.6.8

**Comment by brianpinto91** [comment]
Hi,

You have Python 3.6.8. You need Python version >=3.6.9 and only then you can install this package.

Regards,
Brian

**Comment by Durys** [comment]
Thanks Brian - resolving~.
